openmemory_url: "http://localhost:8765"
user_id: "james"
profiles:
  - hotkey: "ctrl+alt+w"
    app: "work"
    whitelist_titles: []
    whitelist_processes: []
capture_interval_sec: 15
dedupe_ttl_sec: 10
debug_keep_png: false
tesseract_path: 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
mem0_infer: true
mem0_fallback: false

# Phase 4 logging and loop controls
log_path: null  # e.g., "agent.log" to write to file; null for stdout
log_level: "INFO"
foreground_change_only: true


